#! /bin/sh

sxhkd &

# If HDMI-1 connected, split workspaces to both monitors
if [ "$(xrandr | grep "HDMI-0 connected")" ]
then
    bspc monitor DP-4 -d I II III IV V
    bspc monitor HDMI-0 -d VI VII VIII IX X
else
    bspc monitor DP-4 -d I II III IV V VI VI VIII IX X
fi

# Used to make polybar maintain proper workspaces per monitor when going from 2
# to 1 monitor again.. This may include some monitor re-ordering issues
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true


# Sometimes when using an external monitor that is larger than the base laptop
# screen size, padding would be applied to make the nodes the size of the
# laptop resolution - we don't want that, as the nodes should fill out the
# entire height/width of the monitor, so we set all padding to 0.
bspc config top_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc rule -a kitty:scratchy sticky=on state=floating rectangle=widthxheight+Xoffset+Yoffset

bspc config border_width         4
bspc config border_radius        12
bspc config window_gap           12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance 	 true

bspc config normal_border_color '#928374'
bspc config focused_border_color '#ebdbb2'
bspc config presel_border_color '#d79921'
bspc config normal_sticky_border_color '#4e4e4e'
bspc config focused_sticky_border_color '#83a598'
bspc config urgent_border_color '#fb4934'


# --------------------------------
# ------- Non-BSPWM related ------
# --------------------------------

# Set wallpaper
## feh --bg-fill ~/Documents/Wallpapers/gruvbox.png

# Reload .Xresources
## xrdb -load ~/.Xresources

# Launch polybar
~/.config/polybar/launch.sh

# Change from ugly 'X' cursor when hovering over background
xsetroot -cursor_name left_ptr

# Make betterlockscreen generate and cache a background image for locking
## betterlockscreen -u ~/Documents/Wallpapers/gruvbox.png

# ------- Autostart apps ------

# Picom
picom --xrender-sync-fence &

# Dunst
## dunst &

# Dropbox
## dropbox &

# Cmst (connman front-end)
## cmst &

# network-manager-applet
## nm-applet &
